### ISSUE TITLE
Standardizing format of return values.

### ISSUE THREAD

**Issue by JulianGriggs** [talk2cerlin/akamai#2]
Hello Cerlin!

This is a very useful library, so thanks for putting it together!  I wanted to ask what your thoughts would be on standardizing the return format for all of the API actions. As it currently stands, delete(), rmdir(), and upload() all return a response in array format with fields for "code" and "data". The dir() and download() functions on the other hand simply return strings.  For ease of error parsing I would like to standardize all of the API methods to return the array formatted result. I'm happy to implement this and create a PR but wanted to get your stance first as it wouldn't be backwards compatible.

Thanks,
Julian

**Comment by talk2cerlin** [comment]
Hello julian,

Please go ahead and implement this. I will make it as a major release
